version: '3'

services: 

  php:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    image: pereirapy/php:prod
    container_name: php
    networks: 
      - laranet

  nginx_php:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: pereirapy/nginx:php
    container_name: nginx_php
    networks: 
      - laranet
    ports: 
      - "8080:80"

networks: 
  laranet:
    driver: bridge      