FROM golang:1.20-alpine as builder

WORKDIR $GOPATH/src/pereirapy/myapp/

COPY go.mod ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o /go/bin/helloworld

FROM scratch

COPY --from=builder /go/bin/helloworld /go/bin/helloworld

ENTRYPOINT [ "/go/bin/helloworld" ]